/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/clients/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all clients */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            telegram?: string | null;
                            illnesses?: number | null;
                            active?: boolean;
                            /** Format: date-time */
                            createdAt?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        name: string;
                        telegram?: string;
                        illnesses?: number;
                        active?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            telegram?: string | null;
                            illnesses?: number | null;
                            active?: boolean;
                            /** Format: date-time */
                            createdAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/clients/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a client by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            telegram?: string | null;
                            illnesses?: number | null;
                            active?: boolean;
                            /** Format: date-time */
                            createdAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a client */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            telegram?: string | null;
                            illnesses?: number | null;
                            active?: boolean;
                            /** Format: date-time */
                            createdAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a client */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        name?: string;
                        telegram?: string;
                        illnesses?: number;
                        active?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            telegram?: string | null;
                            illnesses?: number | null;
                            active?: boolean;
                            /** Format: date-time */
                            createdAt?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    '/groups/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all groups */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            weekDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                            classTime?: string;
                            durationMin?: number;
                            maxCapacity?: number;
                            classesPerPeriod?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        name: string;
                        weekDays: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                        classTime: string;
                        durationMin: number;
                        maxCapacity: number;
                        classesPerPeriod: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            weekDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                            classTime?: string;
                            durationMin?: number;
                            maxCapacity?: number;
                            classesPerPeriod?: number;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/groups/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a group by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            weekDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                            classTime?: string;
                            durationMin?: number;
                            maxCapacity?: number;
                            classesPerPeriod?: number;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a group */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            weekDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                            classTime?: string;
                            durationMin?: number;
                            maxCapacity?: number;
                            classesPerPeriod?: number;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a group */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        name?: string;
                        weekDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                        classTime?: string;
                        durationMin?: number;
                        maxCapacity?: number;
                        classesPerPeriod?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            weekDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
                            classTime?: string;
                            durationMin?: number;
                            maxCapacity?: number;
                            classesPerPeriod?: number;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    '/enrollments/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll a client in a group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        clientId: string;
                        /** Format: uuid */
                        groupId: string;
                        /** Format: date */
                        enrolledAt: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            enrolledAt?: string;
                            /** Format: date */
                            leftAt?: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/enrollments/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Unenroll a client (set left date) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: date */
                        leftAt: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            enrolledAt?: string;
                            /** Format: date */
                            leftAt?: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    '/subscriptions/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions */
        get: {
            parameters: {
                query?: {
                    client_id?: string;
                    status?: 'active' | 'expired' | 'frozen';
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            periodStart?: string;
                            /** Format: date */
                            periodEnd?: string;
                            classesTotal?: number;
                            classesUsed?: number;
                            amountPaid?: string;
                            /** @enum {string} */
                            status?: 'active' | 'expired' | 'frozen';
                            /** @enum {string|null} */
                            paymentMethod?: 'card' | 'cash' | 'ua_card' | null;
                        }[];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        clientId: string;
                        /** Format: uuid */
                        groupId: string;
                        /** Format: date */
                        periodStart: string;
                        amountPaid: string;
                        /** @enum {string} */
                        paymentMethod?: 'card' | 'cash' | 'ua_card';
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            periodStart?: string;
                            /** Format: date */
                            periodEnd?: string;
                            classesTotal?: number;
                            classesUsed?: number;
                            amountPaid?: string;
                            /** @enum {string} */
                            status?: 'active' | 'expired' | 'frozen';
                            /** @enum {string|null} */
                            paymentMethod?: 'card' | 'cash' | 'ua_card' | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/subscriptions/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a subscription */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a subscription */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        clientId?: string;
                        /** Format: uuid */
                        groupId?: string;
                        /** Format: date */
                        periodStart?: string;
                        amountPaid?: string;
                        /** @enum {string} */
                        status?: 'active' | 'expired' | 'frozen';
                        classesUsed?: number;
                        /** Format: date */
                        periodEnd?: string;
                        /** @enum {string} */
                        paymentMethod?: 'card' | 'cash' | 'ua_card';
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            periodStart?: string;
                            /** Format: date */
                            periodEnd?: string;
                            classesTotal?: number;
                            classesUsed?: number;
                            amountPaid?: string;
                            /** @enum {string} */
                            status?: 'active' | 'expired' | 'frozen';
                            /** @enum {string|null} */
                            paymentMethod?: 'card' | 'cash' | 'ua_card' | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    '/sessions/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions */
        get: {
            parameters: {
                query?: {
                    group_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            sessionDate?: string;
                            sessionTime?: string;
                            cancelled?: boolean;
                            /** Format: uuid */
                            holidayId?: string | null;
                        }[];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/sessions/generate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate sessions for a group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        groupId: string;
                        /** @default 4 */
                        weeks?: number;
                        /** Format: date */
                        fromDate?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            sessionDate?: string;
                            sessionTime?: string;
                            cancelled?: boolean;
                            /** Format: uuid */
                            holidayId?: string | null;
                        }[];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/sessions/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            sessionDate?: string;
                            sessionTime?: string;
                            cancelled?: boolean;
                            /** Format: uuid */
                            holidayId?: string | null;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Cancel or uncancel a session */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        cancelled: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            groupId?: string;
                            /** Format: date */
                            sessionDate?: string;
                            sessionTime?: string;
                            cancelled?: boolean;
                            /** Format: uuid */
                            holidayId?: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    '/attendance/{session_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attendance for a session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            sessionId?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            subscriptionId?: string;
                            present?: boolean;
                            note?: string | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/attendance/{session_id}/mark': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark attendance for a session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        clientId: string;
                        present: boolean;
                        /** Format: uuid */
                        subscriptionId: string;
                        note?: string;
                    }[];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            sessionId?: string;
                            /** Format: uuid */
                            clientId?: string;
                            /** Format: uuid */
                            subscriptionId?: string;
                            present?: boolean;
                            note?: string | null;
                        }[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/holidays/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all holidays */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: date */
                            date?: string;
                            name?: string;
                            affectsAllGroups?: boolean;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a holiday */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: date */
                        date: string;
                        name: string;
                        /** @default true */
                        affectsAllGroups?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: date */
                            date?: string;
                            name?: string;
                            affectsAllGroups?: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/holidays/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a holiday */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            id?: string;
                            /** Format: date */
                            date?: string;
                            name?: string;
                            affectsAllGroups?: boolean;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error?: string;
                            code?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/dashboard/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/electric/{*}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    '*': string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
